name: deploy-eshop-prod
concurrency: eshop-prod

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: eShopRG


jobs:

  build-basket-api:
  
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: basket-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-blazor-client:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: blazor-client
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-catalog-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: catalog-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-identity-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: identity-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-ordering-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: ordering-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-payment-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: payment-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-webshoppingagg:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: webshoppingagg
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-webshoppingapigw:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: webshoppingapigw
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  lint-bicep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bicep linter
      run: az bicep build --file deploy/eshop.bicep

  validate-bicep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        deploymentName: eshop-${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/eshop.bicep
        deploymentMode: Validate
        parameters:
          basketApiImageTag=${{ github.sha }}
          blazorClientImageTag=${{ github.sha }}
          catalogApiImageTag=${{ github.sha }}
          identityApiImageTag=${{ github.sha }}
          orderingApiImageTag=${{ github.sha }}
          paymentApiImageTag=${{ github.sha }}
          webshoppingAggImageTag=${{ github.sha }}
          webshoppingGWImageTag=${{ github.sha }}

  preview:
    runs-on: ubuntu-latest
    needs: [lint-bicep, validate-bicep]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/cli@v1
      name: Run what-if
      with:
        inlineScript: |
            az deployment group what-if \
              --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
              --template-file deploy/eshop.bicep \
              --parameters  basketApiImageTag=${{ github.sha }} \
                            blazorClientImageTag=${{ github.sha }} \
                            catalogApiImageTag=${{ github.sha }} \
                            identityApiImageTag=${{ github.sha }} \
                            orderingApiImageTag=${{ github.sha }} \
                            paymentApiImageTag=${{ github.sha }} \
                            webshoppingAggImageTag=${{ github.sha }} \
                            webshoppingGWImageTag=${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [preview, build-basket-api, build-blazor-client, build-catalog-api, build-identity-api, build-ordering-api, build-payment-api, build-webshoppingagg, build-webshoppingapigw]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Deploy eShop
      with:
        failOnStdErr: false
        deploymentName: eshop-${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/eshop.bicep
        parameters:
          basketApiImageTag=${{ github.sha }}
          blazorClientImageTag=${{ github.sha }}
          catalogApiImageTag=${{ github.sha }}
          identityApiImageTag=${{ github.sha }}
          orderingApiImageTag=${{ github.sha }}
          paymentApiImageTag=${{ github.sha }}
          webshoppingAggImageTag=${{ github.sha }}
          webshoppingGWImageTag=${{ github.sha }}


  loadTest:
    name: Load Test
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: './tests/load-testing/homepage.yaml'
          loadTestResource: 'eShopLoadTests'
          resourceGroup: ${{ env.AZURE_RESOURCEGROUP_NAME }}
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
