name: deploy-eshop-prod
concurrency: eshop-prod

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: eShopRG


jobs:

  build-basket-api:
  
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: basket-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-blazor-client:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: blazor-client
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-catalog-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: catalog-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-identity-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: identity-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-ordering-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: ordering-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-payment-api:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: payment-api
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-webshoppingagg:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: webshoppingagg
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  build-webshoppingapigw:
    uses: qdelamea/eShopOnContainerApps/.github/workflows/service-build.yml@main
    with:
      serviceName: webshoppingapigw
      registryName: acrdw5jt22hnrywq
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  lint-bicep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bicep linter
      run: az bicep build --file deploy/eshop.bicep

  validate-bicep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        deploymentName: eshop-dpl${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/eshop.bicep
        deploymentMode: Validate

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/cli@v1
      name: Run what-if
      with:
        inlineScript: |
            az deployment group what-if \
              --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
              --template-file deploy/eshop.bicep

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: preview
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Deploy eShop
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/eshop.bicep
